INSERT INTO colleges (name, university) VALUES('كلية الشريعة', 6);
INSERT INTO colleges (name, university) VALUES('كلية الهندسة وتكنولوجيا المعلومات', 6);
INSERT INTO colleges (name, university) VALUES('كلية الاقتصاد والعلوم الإجتماعية', 6);
INSERT INTO colleges (name, university) VALUES('كلية العلوم', 6);
INSERT INTO colleges (name, university) VALUES('كلية الزراعة والطب البيطري', 6);
INSERT INTO colleges (name, university) VALUES('كلية الطب وعلوم الصحة', 6);
INSERT INTO colleges (name, university) VALUES('كلية العلوم الإنسانية', 6);
INSERT INTO colleges (name, university) VALUES('كلية العلوم التربوية وإعداد المعلمين', 6);
INSERT INTO colleges (name, university) VALUES('كلية الفنون الجميلة', 6);
INSERT INTO colleges (name, university) VALUES('كلية القانون', 6);

INSERT INTO majors (name, college) VALUES ('أصول الدين', 29);
INSERT INTO majors (name, college) VALUES ('أصول الدين فرعي لغة عربية', 29);
INSERT INTO majors (name, college) VALUES ('الفقه والتشريع', 29);
INSERT INTO majors (name, college) VALUES ('مصارف اسلامية', 29);
INSERT INTO majors (name, college) VALUES ('أنظمة المعلومات الإدارية', 30);
INSERT INTO majors (name, college) VALUES ('أنظمة المعلومات الحاسوبية', 30);
INSERT INTO majors (name, college) VALUES ('الشبكات وأمن المعلومات', 30);
INSERT INTO majors (name, college) VALUES ('الهندسة الصناعية', 30);
INSERT INTO majors (name, college) VALUES ('الهندسة الكهربائية', 30);
INSERT INTO majors (name, college) VALUES ('الهندسة الكيميائية', 30);
INSERT INTO majors (name, college) VALUES ('الهندسة المدنية', 30);
INSERT INTO majors (name, college) VALUES ('الهندسة المعمارية', 30);
INSERT INTO majors (name, college) VALUES ('الهندسة الميكانيكية', 30);
INSERT INTO majors (name, college) VALUES ('علم الحاسوب', 30);
INSERT INTO majors (name, college) VALUES ('علوم الحاسوب بالشراكة مع سوق العمل', 30);
INSERT INTO majors (name, college) VALUES ('هندسة الاتصالات', 30);
INSERT INTO majors (name, college) VALUES ('هندسة البناء', 30);
INSERT INTO majors (name, college) VALUES ('هندسة التخطيط وتكنولوجيا المدن', 30);
INSERT INTO majors (name, college) VALUES ('هندسة الجيومتكس', 30);
INSERT INTO majors (name, college) VALUES ('هندسة الحاسوب', 30);
INSERT INTO majors (name, college) VALUES ('هندسة الطاقة والبيئة', 30);
INSERT INTO majors (name, college) VALUES ('هندسة الميكاترونكس', 30);
INSERT INTO majors (name, college) VALUES ('هندسة علوم المواد', 30);
INSERT INTO majors (name, college) VALUES ('إدارة الأعمال', 31);
INSERT INTO majors (name, college) VALUES ('إدارة الأعمال - فرعي التأمين', 31);
INSERT INTO majors (name, college) VALUES ('اقتصاد - فرعي التأمين', 31);
INSERT INTO majors (name, college) VALUES ('الإذاعة والتلفزيون', 31);
INSERT INTO majors (name, college) VALUES ('الاتصال والإعلام الرقمي', 31);
INSERT INTO majors (name, college) VALUES ('الاتصال والتسويق الرقمي', 31);
INSERT INTO majors (name, college) VALUES ('الاقتصاد', 31);
INSERT INTO majors (name, college) VALUES ('التسويق - فرعي التأمين', 31);
INSERT INTO majors (name, college) VALUES ('الجغرافيا', 31);
INSERT INTO majors (name, college) VALUES ('الخدمة الإجتماعية', 31);
INSERT INTO majors (name, college) VALUES ('العلاقات العامة والاتصال', 31);
INSERT INTO majors (name, college) VALUES ('العلوم السياسية', 31);
INSERT INTO majors (name, college) VALUES ('العلوم المالية والمصرفية', 31);
INSERT INTO majors (name, college) VALUES ('العلوم المالية والمصرفية - فرعي التأمين', 31);
INSERT INTO majors (name, college) VALUES ('المحاسبة', 31);
INSERT INTO majors (name, college) VALUES ('المحاسبة - فرعي التأمين', 31);
INSERT INTO majors (name, college) VALUES ('رئيسي اقتصاد / فرعي علاقات عامة', 31);
INSERT INTO majors (name, college) VALUES ('رئيسي الاتصال والاعلام الرقمي/ فرعي اقتصاد', 31);
INSERT INTO majors (name, college) VALUES ('رئيسي جغرافيا - فرعي جيوماتكس', 31);
INSERT INTO majors (name, college) VALUES ('رئيسي علم النفس/ فرعي إرشاد نفسي', 31);
INSERT INTO majors (name, college) VALUES ('الأحياء البيوتكنولوجيا', 32);
INSERT INTO majors (name, college) VALUES ('الرياضيات', 32);
INSERT INTO majors (name, college) VALUES ('العلوم الحياتية', 32);
INSERT INTO majors (name, college) VALUES ('الفيزياء', 32);
INSERT INTO majors (name, college) VALUES ('الكيمياء', 32);
INSERT INTO majors (name, college) VALUES ('الكيمياء التطبيقية', 32);
INSERT INTO majors (name, college) VALUES ('رئيسي الرياضيات - فرعي تربية', 32);
INSERT INTO majors (name, college) VALUES ('رئيسي الرياضيات – فرعي إحصاء', 32);
INSERT INTO majors (name, college) VALUES ('رئيسي الفيزياء/فرعي الكترونيات', 32);
INSERT INTO majors (name, college) VALUES ('رئيسي رياضيات - فرعي التأمين', 32);
INSERT INTO majors (name, college) VALUES ('رئيسي فيزياء فرعي تربية', 32);
INSERT INTO majors (name, college) VALUES ('رئيسي كيمياء- فرعي تربية', 32);
INSERT INTO majors (name, college) VALUES ('الإنتاج الحيواني وصحة الحيوان', 33);
INSERT INTO majors (name, college) VALUES ('الإنتاج النباتي والوقاية', 33);
INSERT INTO majors (name, college) VALUES ('التغذية والتصنيع الغذائي', 33);
INSERT INTO majors (name, college) VALUES ('الطب البيطري', 33);
INSERT INTO majors (name, college) VALUES ('البصريات', 34);
INSERT INTO majors (name, college) VALUES ('التخدير والإنعاش التقني', 34);
INSERT INTO majors (name, college) VALUES ('التصوير الطبي', 34);
INSERT INTO majors (name, college) VALUES ('التمريض', 34);
INSERT INTO majors (name, college) VALUES ('الصيدلة', 34);
INSERT INTO majors (name, college) VALUES ('الطب البشري "دكتور في الطب"', 34);
INSERT INTO majors (name, college) VALUES ('العلاج الطبيعي', 34);
INSERT INTO majors (name, college) VALUES ('العلوم الطبية الحيوية', 34);
INSERT INTO majors (name, college) VALUES ('العلوم الطبية المخبرية', 34);
INSERT INTO majors (name, college) VALUES ('القبالة', 34);
INSERT INTO majors (name, college) VALUES ('تكنولوجيا التروية القلبية', 34);
INSERT INTO majors (name, college) VALUES ('دكتور صيدلي', 34);
INSERT INTO majors (name, college) VALUES ('علم السمع و النطق', 34);
INSERT INTO majors (name, college) VALUES ('مستحضرات التجميل والعناية بالبشرة', 34);
INSERT INTO majors (name, college) VALUES ('التاريخ', 35);
INSERT INTO majors (name, college) VALUES ('السياحة والآثار', 35);
INSERT INTO majors (name, college) VALUES ('اللغة الانجليزية وآدابها', 35);
INSERT INTO majors (name, college) VALUES ('اللغة العربية وآدابها', 35);
INSERT INTO majors (name, college) VALUES ('اللغة الفرنسية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي التاريخ - فرعي تربية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الإنجليزية وآدابها - فرعي إعداد معلمي اللغة العربية للناطقين بغيرها', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الإنجليزية وآدابها - فرعي ترجمة', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الإنجليزية وآدابها فرعي اللغة العبرية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الانجليزية وآدابها فرعي الدراسات الأمريكية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الانجليزية وآدابها فرعي اللغة الفرنسية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الانجليزية وآدابها فرعي تربية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة العربية وآدابها - فرعي إعداد معلمي اللغة العربية للناطقين بغيرها', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة العربية وآدابها - فرعي اللغة العبرية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة العربية وآدابها فرعي تربية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الفرنسية - فرعي إعداد معلمي اللغة العربية للناطقين بغيرها', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الفرنسية فرعي اللغة الانجليزية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي اللغة الفرنسية – فرعي اللغة العبرية', 35);
INSERT INTO majors (name, college) VALUES ('رئيسي فرنسي فرعي العلاقات العامة', 35);
INSERT INTO majors (name, college) VALUES ('التربية الرياضية - التدريب الرياضي', 36);
INSERT INTO majors (name, college) VALUES ('التربية الرياضية- أساليب التدريس', 36);
INSERT INTO majors (name, college) VALUES ('التعليم الجامع والتربية الخاصة', 36);
INSERT INTO majors (name, college) VALUES ('تخصص المرحلة الأساسية الدنيا', 36);
INSERT INTO majors (name, college) VALUES ('تخصص رياض أطفال', 36);
INSERT INTO majors (name, college) VALUES ('تخصص معلم المرحلة الأساسية العليا -تعليم اللغة الإنجليزية', 36);
INSERT INTO majors (name, college) VALUES ('تخصص معلم المرحلة الأساسية العليا – تعليم اللغة العربية', 36);
INSERT INTO majors (name, college) VALUES ('تخصص معلم المرحلة الأساسية العليا- تعليم اجتماعيات', 36);
INSERT INTO majors (name, college) VALUES ('تخصص معلم المرحلة الأساسية العليا- تعليم التكنولوجيا', 36);
INSERT INTO majors (name, college) VALUES ('تخصص معلم المرحلة الأساسية العليا- تعليم الرياضيات', 36);
INSERT INTO majors (name, college) VALUES ('تخصص معلم المرحلة الأساسية العليا- تعليم العلوم', 36);
INSERT INTO majors (name, college) VALUES ('دبلوم التأهيل التربوي', 36);
INSERT INTO majors (name, college) VALUES ('التصميم الجرافيكي', 37);
INSERT INTO majors (name, college) VALUES ('التصميم الداخلي (ديكور)', 37);
INSERT INTO majors (name, college) VALUES ('الرسم والتصوير', 37);
INSERT INTO majors (name, college) VALUES ('الموسيقى', 37);
INSERT INTO majors (name, college) VALUES ('تصميم الألعاب', 37);
INSERT INTO majors (name, college) VALUES ('فن الخزف', 37);
INSERT INTO majors (name, college) VALUES ('القانون', 38);
